# Generated by Django 6.1.1 on 2026-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('aviable_to_purchase', models.BooleanField(db_index=True, default=True, verbose_name='Доступен для покупки')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
                ('price_in_rubles', models.DecimalField(db_index=True, decimal_places=2, max_digits=8, verbose_name='Цена в рублях')),
            ],
        ),
    ]
